#!/usr/bin/python3
from PIL import Image
from io import BytesIO
import re, base64
import sys

def base64_to_png(codec):
    img = Image.open(BytesIO(base64.b64decode(re.sub('^data:image/.+;base64,', '', codec))))
    img.save(sys.stdout, "PNG")

if __name__ == "__main__":
    codec=sys.stdin.read()
    base64_to_png(codec)
